#!/usr/bin/env bash
# Install the DUO87 deck for the current user, without a venv.
#
# The app deliberately uses system packages (python-pillow, pyqt6, pygobject),
# which do not install cleanly into a venv/pipx, so we install thin launchers
# that run the source with the system Python instead of copying/pip-installing.
# Re-runnable; safe to run again after `git pull`.
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
BIN="$HOME/.local/bin"
CFGDIR="$HOME/.config/duo87"
AUTOSTART="$HOME/.config/autostart"
mkdir -p "$BIN" "$CFGDIR" "$AUTOSTART"

# --- launchers -------------------------------------------------------------
cat > "$BIN/duo87-deck" <<EOF
#!/usr/bin/env bash
# DUO87 tray daemon (generated by install.sh)
export PYTHONPATH="$REPO\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m deck.daemon "\$@"
EOF
chmod +x "$BIN/duo87-deck"

cat > "$BIN/duo87" <<EOF
#!/usr/bin/env bash
# DUO87 stdlib CLI driver (generated by install.sh)
exec python3 "$REPO/duo87.py" "\$@"
EOF
chmod +x "$BIN/duo87"
echo "launchers      -> $BIN/duo87-deck, $BIN/duo87"

# --- config ----------------------------------------------------------------
# The installed daemon runs with no particular cwd, so it reads
# ~/.config/duo87/config.toml. Seed it from a repo-local config.toml once.
if [ -f "$REPO/config.toml" ] && [ ! -f "$CFGDIR/config.toml" ]; then
  cp "$REPO/config.toml" "$CFGDIR/config.toml"
  echo "config         -> copied config.toml to $CFGDIR/config.toml"
elif [ ! -f "$CFGDIR/config.toml" ]; then
  cp "$REPO/config.example.toml" "$CFGDIR/config.toml"
  echo "config         -> seeded $CFGDIR/config.toml from the example (edit it)"
else
  echo "config         -> kept existing $CFGDIR/config.toml"
fi

# --- autostart -------------------------------------------------------------
# XDG entry (GNOME/KDE and any DE that runs XDG autostart).
cat > "$AUTOSTART/duo87-deck.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=DUO87 Deck
Comment=Drive the Womier DUO87 display pad
Exec=$BIN/duo87-deck
Icon=input-keyboard
Terminal=false
X-GNOME-Autostart-enabled=true
EOF
echo "autostart      -> $AUTOSTART/duo87-deck.desktop"

# niri does not run XDG autostart; it uses spawn-at-startup. Add it once.
NIRI="$HOME/.config/niri/config.kdl"
if [ -f "$NIRI" ] && ! grep -q 'duo87-deck' "$NIRI"; then
  printf '\nspawn-at-startup "%s/duo87-deck"\n' "$BIN" >> "$NIRI"
  echo "niri           -> added spawn-at-startup to $NIRI"
elif [ -f "$NIRI" ]; then
  echo "niri           -> spawn-at-startup already present"
fi

# --- Python dependency check (system interpreter, not a venv) --------------
missing=""
for probe in "PIL:pillow" "PyQt6:pyqt6" "gi:pygobject"; do
  mod="${probe%%:*}"
  python3 -c "import $mod" 2>/dev/null || missing="$missing ${probe##*:}"
done
if [ -n "$missing" ]; then
  echo
  echo "MISSING Python modules (needed by the app):$missing"
  if command -v pacman >/dev/null 2>&1; then
    echo "  sudo pacman -S --needed python-pillow pyqt6 python-gobject"
  elif command -v apt >/dev/null 2>&1; then
    echo "  sudo apt install python3-pil python3-pyqt6 python3-gi gir1.2-gdkpixbuf-2.0"
  elif command -v dnf >/dev/null 2>&1; then
    echo "  sudo dnf install python3-pillow python3-pyqt6 python3-gobject"
  else
    echo "  install them with your distro's package manager (pillow, pyqt6, pygobject)."
  fi
fi

# --- udev rule reminder (needs sudo; we cannot do it here) -----------------
if [ ! -f /etc/udev/rules.d/99-duo87.rules ]; then
  echo
  echo "ACTION NEEDED: install the udev rule so your user can reach the pad:"
  echo "  sudo install -m644 \"$REPO/99-duo87.rules\" /etc/udev/rules.d/"
  echo "  sudo udevadm control --reload"
  echo "  sudo udevadm trigger --action=add --subsystem-match=hidraw"
fi

# --- ydotool reminder (for Zoom controls) ----------------------------------
if command -v ydotool >/dev/null 2>&1 \
   && ! systemctl --user is-enabled ydotool.service >/dev/null 2>&1; then
  echo
  echo "For Zoom controls, enable the keystroke daemon:"
  echo "  systemctl --user enable --now ydotool.service"
fi

echo
echo "Done. Start now with:  duo87-deck   (or it will start at next login)."
if ! command -v duo87-deck >/dev/null 2>&1; then
  echo "NOTE: $BIN is not on PATH; add it to your shell profile."
fi
